CREATE DATABASE EVENTDB;
USE EVENTDB;

---  1 Task. UserInfo TABLE ---

CREATE TABLE UserInfo(
EMAILID VARCHAR(100) PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
ROLE VARCHAR(20) NOT NULL CHECK(ROLE IN ('Admin','Participant')),
PASSWORD VARCHAR(20) CHECK(LEN(PASSWORD) BETWEEN 6 AND 20)
);
SELECT * FROM UserInfo;

INSERT INTO UserInfo VALUES('admin@gmail.com','Adminuser','Admin','admin123');
INSERT INTO UserInfo VALUES('Thiru@gmail.com','Thiru','Participant','Thiru@123');
INSERT INTO UserInfo VALUES('Karan@gmail.com','Karan','Participant','Karan@23');
INSERT INTO UserInfo VALUES('Amar@gmail.com','Amar','Participant','Amar@123');
INSERT INTO UserInfo VALUES('Roopa@gmail.com','Roopa','Participant','Roopa123');
INSERT INTO UserInfo VALUES('Bobby@gmail.com','Bobby','Participant','Bobby123');

select * from UserInfo;

CREATE TABLE EVENTDETAILS(
EVENTID INT PRIMARY KEY,
EVENTNAME VARCHAR(50) NOT NULL,
EVENTCATEGORY VARCHAR(50) NOT NULL,
EVENTDATE DATETIME NOT NULL,
DESCRIPTION VARCHAR(225) NULL,
STATUS VARCHAR(20) CHECK(STATUS IN('ACTIVE','IN-ACTIVE'))
);

 -- 2nd Task . EventDetails TABLE --

  CREATE TABLE SPEAKERSDETAILS(
  SPEAKERID INT PRIMARY KEY,
  SPEAKERNAME VARCHAR(50) NOT NULL CHECK(LEN(SPEAKERNAME) BETWEEN 1 AND 50)
  );


  --   4 Task. SessionInfo TABLE  ---
  CREATE TABLE SESSIONINFO(
  SESSIONID INT PRIMARY KEY,
  EVENTID INT NOT NULL,
  SESSIONTITLE VARCHAR(50) NOT NULL,
  SPEAKERID INT NOT NULL,
  DESCRIPTION VARCHAR(225) NULL,
  SESSIONSTART DATETIME NOT NULL,
  SESSIONEND DATETIME NOT NULL,
  SESSIONURL VARCHAR(225),

  FOREIGN KEY (EVENTID) REFERENCES EventDetails(EVENTID),
  FOREIGN KEY (SPEAKERID)REFERENCES SpeakersDetails(SPEAKERID)
  );

  --  5 Task. ParticipantEventDetails TABLE  --

  CREATE TABLE PARTICIPANTEVENTDETAILS(
  ID INT PRIMARY KEY,
  PARTICIPANTEMAILID VARCHAR(100) NOT NULL,
  EVENTID INT NOT NULL,
  SESSIONID INT NOT NULL,
  ISATTENDED BIT CHECK(ISATTENDED IN (0,1)),
  FOREIGN KEY (PARTICIPANTEMAILID) REFERENCES UserInfo(EMAILID),
  FOREIGN KEY (EVENTID) REFERENCES EVENTDETAILS(EVENTID),
  FOREIGN KEY (SESSIONID) REFERENCES SESSIONINFO(SESSIONID)
   );